-- Insert roles into the roles table
INSERT INTO roles (name) VALUES
                             ('ROLE_TEACHER'),
                             ('ROLE_ADMIN'),
                             ('ROLE_STUDENT');

-- Insert into specialities
INSERT INTO specialities (code, description, name) VALUES
                                                       (073, 'Management', 'Management'),
                                                       (075, 'Marketing', 'Marketing'),
                                                       (076, 'Entrepreneurship and Trade', 'Entrepreneurship and Trade'),
                                                       (101, 'Ecology', 'Ecology'),
                                                       (122, 'Computer Science', 'Computer Science'),
                                                       (123, 'Computer Engineering', 'Computer Engineering'),
                                                       (125, 'Cybersecurity and Information Protection', 'Cybersecurity and Information Protection'),
                                                       (131, 'Applied Mechanics', 'Applied Mechanics'),
                                                       (132, 'Materials Science', 'Materials Science'),
                                                       (201, 'Physics', 'Physics'),
                                                       (202, 'Mathematics', 'Mathematics'),
                                                       (203, 'Chemistry', 'Chemistry'),
                                                       (204, 'Biology', 'Biology'),
                                                       (205, 'Statistics', 'Statistics'),
                                                       (206, 'Astronomy', 'Astronomy'),
                                                       (207, 'Geology', 'Geology'),
                                                       (208, 'Environmental Science', 'Environmental Science'),
                                                       (209, 'Engineering Physics', 'Engineering Physics'),
                                                       (210, 'Biomedical Engineering', 'Biomedical Engineering'),
                                                       (211, 'Materials Engineering', 'Materials Engineering');

-- Insert into disciplines
INSERT INTO disciplines (description, name) VALUES
                                                ('Study of the physical universe and its phenomena', 'Physics'),
                                                ('Study of matter, energy, and chemical reactions', 'Chemistry'),
                                                ('Study of living organisms and their interactions', 'Biology'),
                                                ('Study of mathematical theory and its applications', 'Mathematics'),
                                                ('Study of historical events and their impacts', 'History'),
                                                ('Study of human behavior and mental processes', 'Psychology'),
                                                ('Study of societal structures and relationships', 'Sociology'),
                                                ('Study of the principles of design and visual communication', 'Graphic Design'),
                                                ('Study of computer systems and software', 'Computer Science'),
                                                ('Study of human cultures and societies', 'Anthropology'),
                                                ('Study of financial systems and management', 'Economics'),
                                                ('Study of laws and legal systems', 'Law'),
                                                ('Study of environmental systems and conservation', 'Environmental Science'),
                                                ('Study of artistic expression through music', 'Music'),
                                                ('Study of political systems and governance', 'Political Science');



-- Insert into lesson_types
INSERT INTO lesson_types (name) VALUES
                                    ('Lecture'),
                                    ('Seminar'),
                                    ('Laboratory'),
                                    ('Workshop');

-- Insert into users
INSERT INTO users (date_of_birth, email, first_name, last_name, phone_number) VALUES
                                                                                  ('2000-01-15', 'john.doe@example.com', 'John', 'Doe', '0509843286'),
                                                                                  ('1999-12-05', 'jane.smith@example.com', 'Jane', 'Smith', '0669843286'),
                                                                                  ('2001-03-22', 'michael.jones@example.com', 'Michael', 'Jones', '0509143216'),
                                                                                  ('2000-07-10', 'emily.brown@example.com', 'Emily', 'Brown', '0669841111'),
                                                                                  ('1998-09-25', 'david.white@example.com', 'David', 'White', '0995434212'),
                                                                                  ('1997-11-30', 'sarah.wilson@example.com', 'Sarah', 'Wilson', '0992134212'),
                                                                                  ('1996-04-15', 'daniel.martin@example.com', 'Daniel', 'Martin', '0992234212'),
                                                                                  ('1995-06-28', 'olivia.jackson@example.com', 'Olivia', 'Jackson', '0992334212'),
                                                                                  ('1994-12-01', 'james.miller@example.com', 'James', 'Miller', '0509143222'),
                                                                                  ('1995-10-15', 'sophia.lee@example.com', 'Sophia', 'Lee', '0509143233'),
                                                                                  ('2002-01-20', 'william.harris@example.com', 'William', 'Harris', '0509145555'),
                                                                                  ('2001-05-16', 'isabella.clark@example.com', 'Isabella', 'Clark', '0509145532'),
                                                                                  ('2000-08-22', 'mason.walker@example.com', 'Mason', 'Walker', '0954321999'),
                                                                                  ('1999-02-12', 'mia.rodriguez@example.com', 'Mia', 'Rodriguez', '0954321732'),
                                                                                  ('1998-07-25', 'ethan.davis@example.com', 'Ethan', 'Davis', '0954321933'),
                                                                                  ('1997-11-04', 'ava.garcia@example.com', 'Ava', 'Garcia', '0954321211'),
                                                                                  ('1996-09-30', 'jacob.martinez@example.com', 'Jacob', 'Martinez', '0956531999'),
                                                                                  ('1995-03-15', 'charlotte.hernandez@example.com', 'Charlotte', 'Hernandez', '0954222999'),
                                                                                  ('1994-12-01', 'noah.lopez@example.com', 'Noah', 'Lopez', '0694321999'),
                                                                                  ('1993-10-12', 'amelia.anderson@example.com', 'Amelia', 'Anderson', '0692221999'),
                                                                                  ('2002-03-16', 'liam.thomas@example.com', 'Liam', 'Thomas', '0694325199'),
                                                                                  ('2001-01-24', 'harper.johnson@example.com', 'Harper', 'Johnson', '0694185999'),
                                                                                  ('2000-09-07', 'alexander.brown@example.com', 'Alexander', 'Brown', '0614241999'),
                                                                                  ('1999-04-12', 'ella.jones@example.com', 'Ella', 'Jones', '0694321119'),
                                                                                  ('1998-11-20', 'jack.white@example.com', 'Jack', 'White', '0694321111'),
                                                                                  ('1997-06-22', 'lily.green@example.com', 'Lily', 'Green', '0694641461'),
                                                                                  ('1996-08-05', 'benjamin.lee@example.com', 'Benjamin', 'Lee', '0694633461'),
                                                                                  ('1995-02-20', 'zoe.harris@example.com', 'Zoe', 'Harris', '0694633161'),
                                                                                  ('1994-12-18', 'lucas.carter@example.com', 'Lucas', 'Carter', '0694633311'),
                                                                                  ('1993-05-30', 'luna.walker@example.com', 'Luna', 'Walker', '2223334444'),
                                                                                  ('2002-07-25', 'elijah.miller@example.com', 'Elijah', 'Miller', '5556667778'),
                                                                                  ('2001-10-18', 'chloe.davis@example.com', 'Chloe', 'Davis', '8889990001'),
                                                                                  ('2000-03-28', 'logan.jackson@example.com', 'Logan', 'Jackson', '1112223334'),
                                                                                  ('1999-11-01', 'sophie.martinez@example.com', 'Sophie', 'Martinez', '4442556667'),
                                                                                  ('1998-01-15', 'james.carter@example.com', 'James', 'Carter', '7778880001'),
                                                                                  ('1997-12-30', 'arabella.rodriguez@example.com', 'Arabella', 'Rodriguez', '0001112223'),
                                                                                  ('1996-09-12', 'jackson.garcia@example.com', 'Jackson', 'Garcia', '3334445556'),
                                                                                  ('1995-11-05', 'grace.hall@example.com', 'Grace', 'Hall', '6667778889'),
                                                                                  ('1994-06-15', 'logan.hernandez@example.com', 'Logan', 'Hernandez', '9990001112'),
                                                                                  ('1993-04-22', 'natalie.lopez@example.com', 'Natalie', 'Lopez', '2223334442'),
                                                                                  ('2002-08-12', 'evelyn.taylor@example.com', 'Evelyn', 'Taylor', '5554443335'),
                                                                                  ('2001-11-19', 'noah.martin@example.com', 'Noah', 'Martin', '4445556669'),
                                                                                  ('2000-12-03', 'grace.wilson@example.com', 'Grace', 'Wilson', '3332221115'),
                                                                                  ('1999-07-22', 'logan.thompson@example.com', 'Logan', 'Thompson', '2221113335'),
                                                                                  ('1998-06-10', 'sophia.miller@example.com', 'Sophia', 'Miller', '1114445557'),
                                                                                  ('1997-05-20', 'jack.harris@example.com', 'Jack', 'Harris', '6665554446'),
                                                                                  ('1996-03-16', 'aiden.carter@example.com', 'Aiden', 'Carter', '5556667779'),
                                                                                  ('1995-04-10', 'olivia.green@example.com', 'Olivia', 'Green', '7778889991'),
                                                                                  ('1994-08-25', 'elijah.james@example.com', 'Elijah', 'James', '9990001114'),
                                                                                  ('1993-09-05', 'chloe.brown@example.com', 'Chloe', 'Brown', '2224445557'),
                                                                                  ('2002-05-28', 'mia.jackson@example.com', 'Mia', 'Jackson', '4446667779'),
                                                                                  ('2001-06-15', 'michael.smith@example.com', 'Michael', 'Smith', '3337778880'),
                                                                                  ('2000-04-07', 'ella.davis@example.com', 'Ella', 'Davis', '1116669992'),
                                                                                  ('1999-03-22', 'jacob.clark@example.com', 'Jacob', 'Clark', '2225557779'),
                                                                                  ('1998-12-18', 'amelia.wilson@example.com', 'Amelia', 'Wilson', '3334449992'),
                                                                                  ('1997-10-05', 'aiden.miller@example.com', 'Aiden', 'Miller', '4446661113'),
                                                                                  ('1996-07-11', 'michael.carter@example.com', 'Michael', 'Carter', '5557772224'),
                                                                                  ('1995-09-16', 'sofia.harris@example.com', 'Sofia', 'Harris', '6668883335'),
                                                                                  ('1994-10-03', 'james.green@example.com', 'James', 'Green', '7779994446'),
                                                                                  ('1993-06-25', 'chloe.lee@example.com', 'Chloe', 'Lee', '8880005557'),
                                                                                  ('2002-02-14', 'liam.martinez@example.com', 'Liam', 'Martinez', '9991116668'),
                                                                                  ('2001-07-19', 'arabella.davis@example.com', 'Arabella', 'Davis', '1112229992'),
                                                                                  ('2000-10-05', 'noah.johnson@example.com', 'Noah', 'Johnson', '2223337779'),
                                                                                  ('1999-11-30', 'ava.thomas@example.com', 'Ava', 'Thomas', '3334448890'),
                                                                                  ('1998-04-21', 'ethan.lee@example.com', 'Ethan', 'Lee', '4445559992'),
                                                                                  ('1997-12-01', 'mia.jones@example.com', 'Mia', 'Jones', '5556660002'),
                                                                                  ('1996-01-20', 'emily.davis@example.com', 'Emily', 'Davis', '6667771112'),
                                                                                  ('1995-08-25', 'michael.lee@example.com', 'Michael', 'Lee', '7778882223'),
                                                                                  ('1994-05-20', 'julia.white@example.com', 'Julia', 'White', '8889993334'),
                                                                                  ('1993-08-15', 'isaac.martin@example.com', 'Isaac', 'Martin', '9991114445'),
                                                                                  ('1991-08-15', 'maxdiablo@example.com', 'Max', 'Diablo', '9991112245'),
                                                                                  ('1999-01-22', 'alexwhite@example.com', 'Alex', 'White', '9991112266'),
                                                                                  ('1992-04-25', 'jackrasel@example.com', 'Jack', 'Rassel', '9991112125'),
                                                                                  ('1993-05-09', 'matthiew@example.com', 'Matthiew', 'Holland', '9991112111'),
                                                                                  ('1991-10-01', 'lucydarts@example.com', 'Lucy', 'Darts', '9991112555');

-- Insert into admins
INSERT INTO admins (user_id) VALUES
                                 (1),
                                 (2);

-- Insert into groups
INSERT INTO groups (name, speciality_id) VALUES
                                             ('MANA-01', 1),
                                             ('MANA-02', 1),
                                             ('MARK-01', 2),
                                             ('MARK-02', 2),
                                             ('ECO-01', 4),
                                             ('ECO-02', 4),
                                             ('COMP-01', 5),
                                             ('COMP-02', 5),
                                             ('COMP-01', 6),
                                             ('COMP-02', 6),
                                             ('CYBE-01', 7),
                                             ('CYBE-02', 7),
                                             ('APPL-01', 8),
                                             ('APPL-02', 8),
                                             ('MATE-01', 9),
                                             ('MATE-02', 9),
                                             ('PHYS-01', 10),
                                             ('PHYS-02', 10),
                                             ('MATH-01', 11),
                                             ('MATH-02', 11),
                                             ('CHEM-01', 12),
                                             ('CHEM-02', 12),
                                             ('BIOL-01', 13),
                                             ('BIOL-02', 13),
                                             ('STAT-01', 14);


-- Insert into students
INSERT INTO students (group_id, user_id) VALUES
                                             (1, 3),
                                             (2, 4),
                                             (2, 5),
                                             (2, 6),
                                             (3, 7),
                                             (3, 8),
                                             (3, 9),
                                             (4, 10),
                                             (4, 11),
                                             (4, 12),
                                             (5, 13),
                                             (5, 14),
                                             (5, 15),
                                             (6, 16),
                                             (6, 17),
                                             (6, 18),
                                             (7, 19),
                                             (7, 20),
                                             (7, 21),
                                             (8, 22),
                                             (8, 23),
                                             (8, 24),
                                             (9, 25),
                                             (9, 26),
                                             (9, 27),
                                             (10, 28),
                                             (10, 29),
                                             (10, 30),
                                             (11, 31),
                                             (11, 32),
                                             (11, 33),
                                             (12, 34),
                                             (12, 35),
                                             (12, 36),
                                             (13, 37),
                                             (13, 38),
                                             (13, 39),
                                             (14, 40),
                                             (14, 41),
                                             (14, 42),
                                             (15, 43),
                                             (15, 44),
                                             (15, 45),
                                             (16, 46),
                                             (16, 47),
                                             (16, 48),
                                             (17, 49),
                                             (17, 50);

-- Insert into teachers
INSERT INTO teachers (user_id) VALUES
                                   (51),
                                   (52),
                                   (53),
                                   (54),
                                   (55),
                                   (56),
                                   (57),
                                   (58),
                                   (59),
                                   (60),
                                   (61),
                                   (62),
                                   (63),
                                   (64),
                                   (65),
                                   (66),
                                   (67),
                                   (68),
                                   (69),
                                   (70),
                                   (71),
                                   (72),
                                   (73),
                                   (74),
                                   (75);



-- Insert into lessons
INSERT INTO lessons (classroom_number, date, end_time, start_time, discipline_id, lesson_type_id) VALUES
                                                                                                      (101, '2024-09-01', '10:00:00', '08:00:00', 1, 1),
                                                                                                      (102, '2024-09-02', '12:00:00', '10:00:00', 2, 2),
                                                                                                      (103, '2024-09-03', '14:00:00', '12:00:00', 3, 3),
                                                                                                      (104, '2024-09-04', '16:00:00', '14:00:00', 4, 4),
                                                                                                      (105, '2024-09-05', '08:00:00', '16:00:00', 1, 1),
                                                                                                      (106, '2024-09-06', '10:00:00', '08:00:00', 2, 2),
                                                                                                      (107, '2024-09-07', '12:00:00', '10:00:00', 3, 3),
                                                                                                      (108, '2024-09-08', '14:00:00', '12:00:00', 4, 4);

-- Insert into group_lesson
INSERT INTO group_lesson (group_id, lesson_id) VALUES
                                                   (1, 1),
                                                   (1, 2),
                                                   (2, 3),
                                                   (2, 4),
                                                   (3, 5),
                                                   (3, 6),
                                                   (4, 7),
                                                   (4, 8),
                                                   (5, 1),
                                                   (5, 2),
                                                   (6, 3),
                                                   (6, 4),
                                                   (7, 5),
                                                   (7, 6),
                                                   (8, 7),
                                                   (8, 8);

-- Insert into user_role
INSERT INTO user_role (user_id, role_id) VALUES
                                             (1, 1),
                                             (2,1);

-- Assign teachers to disciplines
INSERT INTO teacher_discipline (teacher_id, discipline_id) VALUES
                                                               (1, 1),
                                                               (2, 1),
                                                               (3, 1),
                                                               (4, 2),
                                                               (5, 2),
                                                               (6, 2),
                                                               (7, 3),
                                                               (8, 3),
                                                               (9, 4),
                                                               (10, 4),
                                                               (11, 5),
                                                               (12, 5),
                                                               (13, 6),
                                                               (14, 6),
                                                               (15, 7),
                                                               (16, 7),
                                                               (17, 8),
                                                               (18, 8),
                                                               (19, 9),
                                                               (20, 9),
                                                               (21, 10),
                                                               (22, 11),
                                                               (23, 12),
                                                               (24, 13),
                                                               (25, 14),
                                                               (24, 15);

